### PR TITLE
Update package.json

### PR DESCRIPTION
**Pull request by jjcc1421**

### CODE REVIEW

**Comment by elrumordelaluz** [comment]
hi @jjcc1421 are you going to add tests? 🎉 #5

**Comment by jjcc1421** [comment]
I am starting creating that, I am not sure. But The first step is to have jest.

**Comment by elrumordelaluz** [comment]
sure! feel free to ask what you need.

**Comment by elrumordelaluz** [comment]
I’ll close this to add tests in the next major release.

**Pull request closed without merging**
