### PR TITLE
emotion added

### PR DESCRIPTION
**Pull request by michelson**
Hi , this adds @emotion support. it uses a new file called `styled` and `keyframes` to import export the either emotion or styled-components library.

Thing is, it's not very clear to me how to compile different packages for styled-components or @emotion-styled.

let's discuss it.

thanks

### CODE REVIEW

**Comment by elrumordelaluz** [comment]
> Thing is, it's not very clear to me how to compile different packages for styled-components or @emotion-styled.

I think that is the most challenge thing. Let's investigate a little.

**Comment by g1eny0ung** [comment]
Hi, thanks for the job of reactour. It's really a useful library. May I ask about this PR's progress 👀? I currently use `material-UI` with default `emotion` support. So if reactour can use `emotion` as the peer dependency, the project will not have to include `styled-components` in `package.json`.

**Comment by michelson** [comment]
i've published https://www.npmjs.com/package/reactour-emotion as a workaround

**Comment by aeharding** [comment]
Here's how material-ui allows switching the css engine from emotion to styled-components:

https://next.material-ui.com/guides/styled-engine/#heading-how-to-switch-to-styled-components

May I suggest that this project switch to emotion by default? Especially because projects like material-ui use it by default.

Thanks!

**Comment by elrumordelaluz** [comment]
@aeharding `@emotion` is coming…

**Comment by michelson** [comment]
I think you could build a workspaces library (lerna) and build two packages at once. so you may use a centralized core code and import styled-components from one and emotion for the other.

**Comment by elrumordelaluz** [comment]
Emotion will be the main styling lib. Get in touch in the next days to analyze how to add other libs. Thanks!

**Pull request closed without merging**
