### PR TITLE
Round translate values to avoid text blurring in browser

### PR DESCRIPTION
**Pull request by Nazaretto**
Just add simple Math.round to avoid float values, which causes blurring of helper

### CODE REVIEW

**Comment by niklaskorz** [comment]
This is really important on non-retina displays, thanks for the PR. I hope it's merged soon.

**Comment by niklaskorz** [comment]
Weirdly enough, I am not expierencing this blurriness on the react tour demo although it has fractional position values as well.
It only appears when used in my own code.

**Comment by JonathanFu** [comment]
I got the same blurring issue.
Could someone @elrumordelaluz please merge this change in?

**Comment by elrumordelaluz** [comment]
Should be fixed on `reactour@1.15.5`. Thanks for your patience.

**Pull request closed without merging**
