### PR TITLE
Feature/modularize

### PR DESCRIPTION
**Pull request by belgac**
Modularize components and helpers, use webpack resolve for imports, simplify isOutsideX and isOutsideY to isOutside and remove trailing white spaces

### CODE REVIEW

**Comment by elrumordelaluz** [comment]
thanks @belgac, the fact to _modularize_ the _Components_ was in mind at the moment but I could avoid a 📁 folder with an `index.js` per _Component_ but, something like  `components/CloseButton.js`and so on … Maybe could be useful a folder structure for the `*Mask`s. 
Did you find any advantage to use folder structure?

Absolutely agree with the `isOutside` changes instead.

**Comment by belgac** [comment]
This structure is more a personal habit than a real necessity, it s just that once tests are implemented and lifecycle events are modularized to their own files (and in some other cases than this library redux reducers, actions and constants are implemented or a repo publishes multiple npm packages through lerna) it s more readable imo to have even the simple components following the same structure as the complex ones

**Comment by elrumordelaluz** [comment]
> This structure is more a personal habit than a real necessity

Supposed that, thanks for the proposal, will review a little probably next week and eventually merge.

>  it s just that once tests are implemented 

🤔 #5 

> and lifecycle events are modularized to their own files

What do you mean?

Last, probably we won't use other state management that the internal `react` state.
Thanks again for the _inputs_ to improve the library in different aspects.

**Comment by belgac** [comment]
Hi,

Yes i don't think a state managment library is necessary that's what i meant.

When i talk about modularizing lifecycle events i'm talking about the onComponentWillMount methods and such that i like to put in separate files and wrap with an HoC that integrates them so the beef of the component is integrated in a pure function instead of a class

**Comment by belgac** [comment]
I implemented your structure for the time being as there is no need for my structure right now

**Comment by elrumordelaluz** [comment]
thanks @belgac for the amount of work you are doing, will review asap.

**Comment by elrumordelaluz** [comment]
Thanks @belgac, great work!

A lil thing, could we remove `;` to mantain the same _style_?

**Comment by belgac** [comment]
Hello where exactly should i remove the ';'?

**Comment by belgac** [comment]
Could you implement a clear styleguide for js (something that works with https://github.com/prettier/prettier-eslint)

**Comment by elrumordelaluz** [comment]
> Could you implement a clear styleguide for js

Love to make it in a near future, for now is not a problem for me to have different styles, won't block the `merge` at lead from my POV

**Comment by elrumordelaluz** [comment]
I’ll close this to apply the new structure in the next major release.

**Pull request closed without merging**
