### PR TITLE
fix a problem in the console

### PR DESCRIPTION
**Pull request by msliva**
fix a problem in the console: Cannot read property 'getBoundingClientRect' of null
Steps how to reproduce:
1 open and close reactour.
2.change DOM with elements which are defined in steps[{selector..
3. in browser console is error

### CODE REVIEW

**Comment by elrumordelaluz** [comment]
Hi @msliva,
Could you explain a little bit more this part
> change DOM with elements which are defined in steps[{selector..

to be able to reproduce your issue.
thanks,

**Comment by msliva** [comment]
Hi @elrumordelaluz I have recorded for you a video which is better than 1000 words. 
https://www.youtube.com/watch?v=MLOchRCsZpU&feature=youtu.be

This is my issue before my fix.

**Comment by elrumordelaluz** [comment]
Thanks @msliva for the video. Yes, you are removing the `button` when opens the _Global filters_ sidebar. Since the _Tour_ expect to continue from the last step open, can't calculate the sizes for the _Masks_ and so on… Some considerations:
- Why don't you try with `startAt={0}` (only in case you don't care about the last `step` open)
- I'm not sure the solution is to check `if (this.helper) {}` since the calculation issuie is related to the `node`. 

I'll continue to analyse ways to avoid similar situations.

Why did you close the PR? Do you want to open an _issue_ to track the state of this?

Let me know,

**Comment by adamsoffer** [comment]
I'm running into this error as well. What was the solve?

**Comment by adamsoffer** [comment]
Here's a hacky workaround. Set a key on the tour component and increment it onRequestClose. This will destroy the old component instance and a create new one.

**Pull request closed without merging**
