### PR TITLE
Add showArrow config

### PR DESCRIPTION
**Pull request by xs9627**
Implement of #98
Use like this,
`<Tour
          ...
          showArrow
          arrowSize={12}
/>`

### CODE REVIEW

**Comment by aqarain** [comment]
Why are you not merging it?

**Comment by sendz** [comment]
we are waiting for this.

**Comment by nelsonwong1012** [comment]
@xs9627 Can you resolve the conflicts when you get a chance? Thanks!

**Comment by xs9627** [comment]
@nelsonwong1012 Done.

**Comment by ketewan** [comment]
Could this feature be at least added to stable v1-branch version, please? I really need it.

**Comment by abumuawiyah** [comment]
@xs9627 @nelsonwong1012 
any updates about this?

**Comment by Anwardo** [comment]
@elrumordelaluz would love this feature to be implemented. Any specific reason this wasn't merged yet?

**Comment by joanargarrido** [comment]
Any updates on this?

**Review by tsachit — APPROVED** [review]

**Comment by tsachit** [comment]
Can you resolve conflict and merge it?

**Comment by hrhrsdn** [comment]
any plans in merging this PR?

**Comment by elrumordelaluz** [comment]
This is now possible setting _Popover_ styles, using the **new v2 version** released under scoped `@rectour` package name, please try `npm i @reactour/tour`. Every feedback super welcome, thanks!

Take a look at this [demo](https://reactour.vercel.app/#custom-styles)

**Pull request closed without merging**
