### PR TITLE
add disableFocusLock prop

### PR DESCRIPTION
**Pull request by bellsml**
Focuslock component used by Reactour sometimes closes menus, dropdowns and modals, affecting page behavior.

### CODE REVIEW

**Comment by PeterKottas** [comment]
Hello all! What is the status of this? I've seen similar problems. I wanted to open a PR but I can see this was already implemented. Is there a reason for it now being merged?

**Comment by PeterKottas** [comment]
Also, I am curious if you managed to find any workaround for the time being @bellsml . I tried using FreeFocusInside explained in more detail [here](https://github.com/theKashey/react-focus-lock#focus-fighting) with no luck.

**Comment by elrumordelaluz** [comment]
Hi @PeterKottas and @bellsml.
First of all, I'm sorry to `focus` :) this _Issue_ just now and not before. No problem at all with that implementation. Mind any of you implement the same _behaviour_ to PR in the `v1` which is the _stable_ branch published. The idea for the `v2` is to remove the lib to replace with another or play with some hooks, since there were lots of _issues_ related on `focus`.

Hope you understand and thanks you!

**Comment by bellsml** [comment]
@PeterKottas 
I'm using the repository I forked for now...

**Comment by bellsml** [comment]
@PeterKottas 
I'm using the repository I forked for now...

**Comment by PeterKottas** [comment]
@elrumordelaluz great news indeed! :) @bellsml would you be able to update the PR? Forking and using that is understandably an option but not for the long run. Best to have it in here! Cheers guys ;)

**Comment by bellsml** [comment]
@PeterKottas 
yes, I agree. 
the project I'm working on is still under development

@elrumordelaluz 
Sorry, now I realized I was doing everything on the master branch.
I had to do another PR for v1.

Please check if I got it right this time:
https://github.com/elrumordelaluz/reactour/pull/253

**Pull request closed without merging**
